experiment_info:
  - "frame_id": "human_0/odom"
    "client_topic": "human_0/move_base"
    "points": [[8.0, 8.0, 0.0],
               [1.5, 2.0, 0.0],
               [8.0, 8.0, 0.0]]
  
  - "frame_id": "human_1/odom"
    "client_topic": "human_1/move_base"
    "points": [[9.0, 9.0, 0.0],
               [2.0, 8.0, 0.0],
               [1.5, 5.2, 0.0]]
