object_list:
  - person
  - tie
  - bottle
  - glass
  - bowl
  - chair
  - couch
  - plant
  - table
  - tv
  - laptop
  - mouse
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refigerator
  - book
  - vase
  - scissors