goal_locations:
  fridge:
    x: -3.5
    y: 4.3

  microwave:
    x: -1.0
    y: 4.3

  coffe_machine:
    x: 0.5
    y: 4.3

  cabinet:
    x: 1.1
    y: 4.3

  table:
    x: -1.0
    y: 1.5

  start:
    x: -2.0
    y: -1.0
